### ISSUE TITLE
still getting Value cannot be null. (Parameter 'path1') with .NET 6 and nuget 3.0.344

### ISSUE THREAD

**Issue by zoinkydoink** [ligershark/WebOptimizer#210]

**Comment by Naziur-R-Enosis** [comment]
Recently we are trying to upgrade our project to .NET 6. And we are also facing the same issue. The sad part is that we came to know about this library from the [ms doc](https://docs.microsoft.com/en-us/aspnet/core/client-side/bundling-and-minification?view=aspnetcore-6.0). Did you find any solution/workaround?

**Comment by zoinkydoink** [comment]
downloaded the source, changed the one line thatas causing it, and currently using this customized project in my solution as a reference library until this is fixed then we will switch to nuget

**Comment by Naziur-R-Enosis** [comment]
@zoinkydoink Can you please let me know the changes you did to fix the issue? That would be very generous of you.

**Comment by zoinkydoink** [comment]
https://ufile.io/bhtf2nfx should be good for 30 days from now, i cant remember the changes I made

i might have even grabbed it from a suggestion by another user, its been a while

**Comment by erlendandenaes** [comment]
I hit this issue a while back, and after a bit of digging I found that it failed when we tried to minify .css files with content similar to this:

`background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" ...`

Commenting the offending lines out did not help, as it still matched the regex in CssFingerprinter.cs. Deleting the lines resolved the issue.

Just leaving it here in case it may help in reproducing and fixing the error.

**Comment by MeikelLP** [comment]
I found out that the issue is related to ASP NET Core 6 changed their default file provider to a [CompositionFileProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.fileproviders.compositefileprovider) which includes the [PhysicalFileProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.fileproviders.physicalfileprovider) and a [ManifestEmbeddedFileProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.fileproviders.manifestembeddedfileprovider).

ASP.NET Core 5 had only a `PhysicalFileProvider` which worked fine because it does not valide the file's existance. The CompositionFileProvider does.

You can quick fix this with importing the project into your solution for now and change the following line:

[GetFileprovider](https://github.com/ligershark/WebOptimizer/blob/c42a7c2dc0790df4df8f6dc70bc1db6dbfe1afd2/src/WebOptimizer.Core/Asset.cs#L263)

to

```csharp
return asset.GetCustomFileProvider(env) ?? new PhysicalFileProvider(env.WebRootPath);
```
